### ISSUE TITLE
Support for ontology term lookup

### ISSUE THREAD

**Issue by agbeltran** [ISA-tools/isa-api#1]

**Comment by djcomlab** [comment]
Can a description be added for this issue?

**Comment by agbeltran** [comment]
This refers to support ontology annotations when completing the values for an ISA experimental description by linking to ontology services such as BioPortal, OLS, LOV. This functionality is already implemented in ISAcreator/OntoMaton.

**Comment by djcomlab** [comment]
Sure, but how does this translate to something programmable? Descriptions on issues like this are really needed so features can be better defined, because just mapping things to what ISAcreator or anything else can or can't do doesn't help.

For example, let's say we're picking a term for something like Study Protocol Type 'extraction', I guess we need to know what steps are needed, in terms of the level of the API, to go about getting the rest of the information to complete, which in our ISA model is the term accession (http://purl.obolibrary.org/obo/OBI_0302884) and term source (which should already be chosen anyway already in the Ontology Source Reference bit). But then this doesn't really amount to 'ontology term lookup' since there's no looking up.

**Comment by agbeltran** [comment]
Of course! Let's discuss it next week so that the spec can be written.
