### ISSUE TITLE
ISACreator XML assay templates 

### ISSUE THREAD

**Issue by vedina** [ISA-tools/isa-api#145]
Could you tell what is the fate of the XML assay templates ISACreator / ISAConfigurator were using ? Are they being used in the Python isa-api framework ? If not, what is the recommended way to define assay templates ?

**Comment by djcomlab** [comment]
At the moment we still use the XML ISA Configuration files to validate ISA-Tab files, and there is not plan to remove support for this.

I've been working on creating a kind of ISA JSON configuration to validate ISA JSON content, since the XML configurations are really designed for the ISA-Tab, but the ISA JSON configurations are still in early stages of development so are not fully working yet.

So for the XML stuff - please be assured is not going anywhere!

**Comment by vedina** [comment]
Thanks!
