### ISSUE TITLE
Use ISAdatasets repository as primary repository for tab and json examples

### ISSUE THREAD

**Issue by agbeltran** [ISA-tools/isa-api#183]
In order not to have datasets repeated in the different code packages, we have created the http://github.com/ISA-tools/ISAdatasets

This ticket is to consider ISAdatasets as the primary repository of ISA examples and consider moving the datasets in the ISA-API to that repository.

**Comment by agbeltran** [comment]
This is related to this is the Github adapter work, as it can be used to bring in the required datasets. 
https://isatools.readthedocs.io/en/latest/github.html

**Comment by djcomlab** [comment]
After a bit of wrangling, I don't think it makes sense to utilize the Github storage adapter in the tests.

In order to ensure tests are run efficiently, the test data needs to be downloaded only once before running the whole test suite. To use the storage adapter in the test means downloading when a test module is loaded, which can happen many times. Refactoring tests into big test modules makes the tests code not so easy to manage.

**Comment by djcomlab** [comment]
A possible solution would be to clone ISAdatasets GitHUb repo into the tests/data directory (by using Git directly) before running the tests. This can probably be integrated into the Travis CI build quite straightforwardly.

**Comment by djcomlab** [comment]
Test data moved (in tests branch); example data in master branch of ISAdatasets
