### ISSUE TITLE
Integrate export to W4M format

### ISSUE THREAD

**Issue by pkrog** [ISA-tools/isa-api#240]
Take code from `isatab2w4m.py` script from [Metabolights downloader]((https://github.com/workflow4metabolomics/mtbls-dwnld)), and integrate it into isa-api.

**Comment by djcomlab** [comment]
Thanks @pkrog, I will take a look!

**Comment by pkrog** [comment]
Hi @djcomlab ,
Please, tell if I can be of any help for the integration. I could do some of the coding or debugging.
Pierrick

**Comment by pkrog** [comment]
Also, I could integrate some of the tests I run in mtbls-dwnld.

**Comment by djcomlab** [comment]
Hi @pkrog sure that would be great if you could add some tests into the ISA API project as I'm not too familiar with the W4M output.

The way out ISA API tests work is that we add any test data we need to https://github.com/ISA-tools/ISAdatasets/ and if testing locally with check this out of Github to `tests/data`. Travis CI also checks this out to run the tests on there.

In the tests themselves they refer to the directories using the constants defined in https://github.com/ISA-tools/isa-api/blob/develop/isatools/tests/utils.py If you could take a look at an example test in https://github.com/ISA-tools/isa-api/blob/develop/tests/test_isatab.py you can see how we do it.

I've made some minor modifications to your code into https://github.com/ISA-tools/isa-api/blob/develop/isatools/convert/isatab2w4m.py in ISA API to allow API calls via `isatab2w4m.convert()`

**Comment by djcomlab** [comment]
Hi @pkrog can you confirm what input the `isatab2w4m` converter needs?

It needs the ISA-Tab files but also the MAF file right? I tried to run the converter on MTBLS1 but it failed.

**Comment by pkrog** [comment]
Hi @djcomlab , yes it takes the s_*, a_* and m_* files. I'n writing now a test in isa-api, so when it's ready you will have an example to read.

**Comment by djcomlab** [comment]
Great, thanks @pkrog!

**Comment by pkrog** [comment]
Hi @djcomlab ,
I've discovered something weird when testing isatab2w4m with study MTBLS30. The sample names returned aren't in the same order on each run. I've looked at the first sample name in the assay (`assay.samples[0]`) several times and have values like `SRC-1+/+ Fed_rep2_heart`, `SRC-1-/- Fasted_rep5_liver` or `SRC-2+/+ Fed_rep5_heart` returned. How is it possible? Should the samples not always be in the same order at the samples column in the file?

**Comment by djcomlab** [comment]
Hi @pkrog -

This is true, actually all of the lists of material (`sources`, `samples`, `other_material`) and `data_files` may not guarantee the order.

This is because when parsing from the ISA-Tab the algorithm creates a `dict` to map references from the assay table files to the sample objects already created (after parsing the study file). As `dict`s do not preserve order, when the the sample objects are loaded into the `Assay` object `samples` list using `.values()` you may see the order of the list might change when running multiple times.

The ISA Abstract Model does not assume the order is important in the lists of materials since there is no concept of a table or rows in the ISA model objects and everything is referenced in a OO style.

If you need consistency in the order list, you'll need to do a sort on the sample name as key.

**Comment by pkrog** [comment]
Ok, thanks, so I'll sort by myself. However would it not be better to ensure we have the same order in memory than in the files. Would not users expect to have this order respected in memory, as well as in conversions/exports? It is hard to examine data when they are mixed up.

**Comment by djcomlab** [comment]
I can fix this to return in a more predictable order based on the sample key, it shouldn't be too much of a problem...

**Comment by pkrog** [comment]
That would be great, thanks !

**Comment by pkrog** [comment]
I you point my to right place, I could also do it for you if you wish.

**Comment by djcomlab** [comment]
Already done, please pull on `develop` branch and try it out.

**Comment by pkrog** [comment]
Cool ! That works, thanks.

**Comment by djcomlab** [comment]
Feature merged with test, further tests can be added down the line but going to close issue now.
