### ISSUE TITLE
API error with sample BII-I-1 Study

### ISSUE THREAD

**Issue by nsadawi** [ISA-tools/isa-api#301]
Hi,
When I load the `BII-I-1` study using:
`isa = isatab.load('/Path/To/BII-I-1/')`
and then do:
`isatab.dump(isa_obj=isa, output_path='/Path/to/BII-I-1/')`
It throws:
`'Process' object has no attribute 'array_design_ref'`

Thanks,
Noureddin

**Comment by djcomlab** [comment]
Hi @nsadawi, can you confirm where you're getting your BII-I-1 sample data from so I can check this?

**Comment by nsadawi** [comment]
@djcomlab it's the one that comes with `ISACreator` .. I have `version 1.7.7`

**Comment by djcomlab** [comment]
@nsadawi OK thanks, will check it out.

**Comment by nsadawi** [comment]
@djcomlab .. Great thanks .. I remember even loading complained .. looks like the study was missing a protocol or something like that!

**Comment by djcomlab** [comment]
@nsadawi It's very possible... the example datasets we have, and even some of the MetaboLights ones, are not always to be taken as 100% correct... I'll check it and let you know!

**Comment by djcomlab** [comment]
Hi, the version of BII-I-1 in ISAcreator 1.7.7 has quite a lot of validation warnings and at least one error, so I wouldn't rely on this. The ISA-API is tested against BII-I-1 taken from https://github.com/ISA-tools/ISAdatasets/tree/tests/

This isn't something we're going to fix in ISA-API (since it's a test data issue in an old version of ISAcreator) so will close this issue.
