### ISSUE TITLE
Error parsing investigation file MTBLS213

### ISSUE THREAD

**Issue by gabrielctn** [ISA-tools/isa-api#306]
Hi,
I'm running a workflow on multiple MTBLS studies which is using the docker container `container-registry.phenomenal-h2020.eu/phnmnl/isa2w4m`. This tool is directly using the isatab2w4m script that is why i'm opening this issue here.

It looks like there is a problem with the study [MTBLS213](https://www.ebi.ac.uk/metabolights/MTBLS213) while parsing the investigation file. The file however passed the isacreator validator (@sneumann) and looks normal.

This is the incriminated command:
```
docker run -v /home/gcretin/Internship_IPB/phnmnl_IPO_workflow/:/isa_files/ container-registry.phenomenal-h2020.eu/phnmnl/isa2w4m -i /isa_files/studies/MTBLS213 -s /isa_files/output/MTBLS213/a_arpe_george_neg_metabolite_profiling_mass_spectrometry/sample-output.tsv -v /isa_files/output/MTBLS213/a_arpe_george_neg_metabolite_profiling_mass_spectrometry/variable-output.tsv -m /isa_files/output/MTBLS213/a_arpe_george_neg_metabolite_profiling_mass_spectrometry/matrix-output.tsv -f 'a_arpe_george_neg_metabolite_profiling_mass_spectrometry.txt'
```

This is the output error:
```
Traceback (most recent call last):
  File "/files/isa2w4m/isa2w4m.py", line 9, in <module>
    isatab2w4m.main()
  File "/files/isa-api/isatools/convert/isatab2w4m.py", line 574, in main
    var_na_filtering    = args_dict['var_na_filtering']
  File "/files/isa-api/isatools/convert/isatab2w4m.py", line 547, in convert
    all_assays     = all_assays)
  File "/files/isa-api/isatools/convert/isatab2w4m.py", line 437, in convert2w4m
    study = select_study(investigation_file, study_filename)
  File "/files/isa-api/isatools/convert/isatab2w4m.py", line 131, in select_study
    investigation = load_investigation(investigation_file)
  File "/files/isa-api/isatools/convert/isatab2w4m.py", line 338, in load_investigation
    investigation = ISATAB.load(f)
  File "/files/isa-api/isatools/isatab.py", line 3105, in load
    df_dict = read_investigation_file(FP)
  File "/files/isa-api/isatools/isatab.py", line 1182, in read_investigation_file
    next_sec_key='STUDY CONTACTS'
  File "/files/isa-api/isatools/isatab.py", line 1104, in _build_section_df
    comment='#').dropna(axis=1, how='all')
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 455, in _read
    data = parser.read(nrows)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 1069, in read
    ret = self._engine.read(nrows)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 2236, in read
    content = self._get_lines(rows)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 2980, in _get_lines
    row_num=self.pos + rows + 1)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 2726, in _next_iter_line
    self._alert_malformed(msg, row_num)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 2685, in _alert_malformed
    raise ParserError(msg)
pandas.errors.ParserError: '	' expected after '"'
```

**Comment by djcomlab** [comment]
Hi, I've investigated this and the problem is in the MTBLS213 investigation file on line 72 that contains this piece of text in one of the cells:
```
xcmsSet(method=centWave"", ppm=30, peakwidth=c(5,20)); retcor(method=""obiwarp"", profStep=0.1
```
Since the Metabolights ISA-Tab files use speech marks around all the cells, this confuses the current implementation of the ISA-API parser that relies on Pandas to load the tab-separated cells.

**Comment by gabrielctn** [comment]
Oh I see, that was unexpected, I would never have thought to look there for a mistake.
The quick fix is doing the job, now the parser is no more unhappy. I will see for giving feedback to the authors of the study, or just fixing it locally.
Thanks for the help !

**Comment by djcomlab** [comment]
No problem, happy to have helped!

**Comment by djcomlab** [comment]
It's worth noting that in MTBLS118, the protocol descriptions use HTML encoding, so really if this is the standard practice used by Metabolights, then the speech marks in the wrong place should be dealt with on the curation side and actually encoded as HTML as suggested.

Sure, we can make it drop whitespace, but really the issue comes from inaccuracy of the data entry. Warnings/errors should happen rather than let junky data exist silently when read by the parser.

MTBLS105 has a range of problems if you run it through the validator - this error you're finding is because half of `a_mtbls105_GC_Q_mass_spectrometry.txt`'s MS Protocol REF column has no values when I suspect it's supposed to have the value `mass spectrometry` all the way down.

My colleague @proccaserra has documented a bunch of problems in the Metabolights ISA-Tabs so I would encourage you to check if the content looks correct first before raising it as a parsing issue in ISA-API (and file a new issue with on new problems since this particular Github issue was originally about MTBLS213; or check with the Metabolights team first if it looks like a data problem).

**Comment by sneumann** [comment]
So @khaug should add such tests to the MTBLS Validation page. Should be easy to do and ensure parsability of studies ... Yours, Steffen

**Comment by gabrielctn** [comment]
Thank you @djcomlab yes it looks like the easiest way to solve _most_ problems would be to do the check at the studie's validation step.

**Comment by khaug** [comment]
We currently validate the protocol text to ensure it is parsed correctly for both ISAcreator and MetaboLights. For MTBLS213 there is a correct number of double-quotes for this purpose, but obviously not for the use case above. 

The curation tool adds the surrounding quotes, then the submitter and/or we adds the quotes inline as and when needed. We have been using HTML for layout purposes, but we recognise this is not ideal. We consider other options with our new online editor. How data is entered today is not something we can easily control with out current submission system.

In the meantime please let us know on metabolights-help@ebi.ac.uk so we can deal with these issues when they arise.
