### ISSUE TITLE
Factor values issue

### ISSUE THREAD

**Issue by bedroesb** [ISA-tools/isa-api#339]
I stumbled across a problem with BrAPI 2 ISA:

If I add 2 different FactorValues (modalities) with the same factor name, two columns are made in the study file (which is correct), but in both columns the last factor value that is added is filled in.
An example:

```python
f = StudyFactor(name='water regimen', factor_type=OntologyAnnotation(term='water regimen'))
fv = FactorValue(factor_name=f, value=OntologyAnnotation(term='jobau_wellwatered_10-21DAS', term_source="",  term_accession=""))

this_isa_sample.factor_values.append(fv)

f = StudyFactor(name='water regimen', factor_type=OntologyAnnotation(term='water regimen'))
fv = FactorValue(factor_name=f, value=OntologyAnnotation(term='jobau_wellwatered_3-9DAS', term_source="",  term_accession=""))

this_isa_sample.factor_values.append(fv)

isa_study.samples.append(this_isa_sample)
```

This will be outputted in the study file as:

Factor Value[water regimen]0 | Factor Value[water regimen]1
-- | --
jobau_wellwatered_3-9DAS | jobau_wellwatered_3-9DAS

The problem is not there when different factor names are used.

**Comment by proccaserra** [comment]
@bedroesb thx for reporting. investigating now. I would have  expected  the second invocation of the `f = StudyFactor(name='water regimen'...` to simply squash the previous one.

**Comment by bedroesb** [comment]
a solution on my side would be to concatenate the modalities with a comma if the factor is the same for an observationunit.

**Comment by DanFaria** [comment]
> a solution on my side would be to concatenate the modalities with a comma if the factor is the same for an observationunit.

Given that, in principle, you should have a single value/modality per factor per observation unit in MIAPPE, this seems to me the more sensible solution for the BrAPI2ISA conversion when BrAPI has two or more values for the same factor and the same observation unit. I would opt for that representation regardless of the problem on the side of ISA.

**Comment by proccaserra** [comment]
@DanFaria @bedroesb can you define what you mean by `modality` in this context?

I guess the issue will be to understand when an observation is made (ie was it during jobau_wellwatered_3-9DAS regimen or doing jobau_wellwatered_10-21DAS regimen) or after both? I presume in that particular case, only the 'date of observation' will provide the answer, since the factor values are string, with no further formalization.

concatenate would work , not a pb for ISA here as far as I can tell

**Comment by bedroesb** [comment]
Treatments are linked to the observationunits, while timestamps are linked to the observations, so I guess the best option is to concatenate them to end up with 1 string as modality for the water regime factor.

**Comment by DanFaria** [comment]
modality = factor value
The latter is the more precise term, but we have been using the former as a synonym.

**Comment by bedroesb** [comment]
I know that, 

> If I add 2 different FactorValues (modalities) with the same factor name, two columns are made in the study file (which is correct), but in both columns the last factor value that is added is filled in.

But I already discussed this edge case with @PapoutsoglouE  to actually concatenate the modalities if their corresponding Factors are the same (within the same observation unit).

**Comment by DanFaria** [comment]
The above was in reply to Philippe's question (I know you know it)  :)

**Comment by proccaserra** [comment]
- write a test for this with similar code
- write documentation to clarify invocation

**Comment by Zigur** [comment]
Not sure about the status of this one @proccaserra

**Comment by proccaserra** [comment]
@Zigur this can be closed as soon as I have updated the documentation.

**Comment by bedroesb** [comment]
@proccaserra that is some fast documentation writing ;)

**Comment by Zigur** [comment]
sorry, I misunderstood what you wrote...thought that docs had already been written

**Comment by proccaserra** [comment]
@bedroesb  ahaha, yeah :) but we can close this issue as the code works as expected. I'll clarify that documentation point which tripped your initial conversion. 

To specify more than one `factor level` associated with a `study factor (independent variable`, do make sure the create multiple instances of ISA `FactorValue` objects.

so DON'T do the following 
```python
f = StudyFactor(name='water regimen', factor_type=OntologyAnnotation(term='water regimen'))
fv = FactorValue(factor_name=f, value=OntologyAnnotation(term='jobau_wellwatered_10-21DAS', term_source="",  term_accession=""))

this_isa_sample.factor_values.append(fv)

f = StudyFactor(name='water regimen', factor_type=OntologyAnnotation(term='water regimen'))
fv = FactorValue(factor_name=f, value=OntologyAnnotation(term='jobau_wellwatered_3-9DAS', term_source="",  term_accession=""))

this_isa_sample.factor_values.append(fv)

> isa_study.samples.append(this_isa_sample)
```

instead DO:
```python
f = StudyFactor(name='water regimen', factor_type=OntologyAnnotation(term='water regimen'))
flevel1 = FactorValue(factor_name=f, value=OntologyAnnotation(term='jobau_wellwatered_10-21DAS', term_source="",  term_accession=""))
flevel2 = FactorValue(factor_name=f, value=OntologyAnnotation(term='jobau_wellwatered_3-9DAS', term_source="",  term_accession=""))

this_isa_sample.factor_values.append(fv)
this_isa_sample.factor_values.append(fv)
```

This will output:
Factor Value[water regimen]0 | Factor Value[water regimen]1
-- | --
jobau_wellwatered_10-21DAS | jobau_wellwatered_3-9DAS

I understand this is still not what you want. What you want is something like:
Factor Value[water regimen]| 
-- | 
jobau_wellwatered_10-21DAS; jobau_wellwatered_3-9DAS |

But this is currently not allowed/supported by the ISA-API, simply because it is odd to have 2 factor levels for the same variable without specifying an treatment order (as it seems to be a repeated treatment, rather than a concomitant one)

**Comment by bedroesb** [comment]
@proccaserra thank you for the explanation!

**Comment by proccaserra** [comment]
@proccaserra to add to the isa-api jupyterbook doc
